#!/usr/bin/env node
// Generates src/index.ts — a barrel of re-exports for every generated
// io.altessa proto module. Run automatically by the `prebuild` npm script,
// so the barrel always matches the generated tree in src/gen and never
// drifts when proto files are added or removed upstream.
//
// DO NOT edit src/index.ts by hand — edit this generator instead.
//
// Alias naming: the path under `src/gen/io/altessa/` with `_pb.ts` stripped
// and segments joined by `_`; a `<pkg>/<ver>/<pkg>` triple collapses to
// `<pkg>_<ver>` (e.g. badrequest/v1/badrequest -> badrequest_v1).

import { readdirSync, writeFileSync, existsSync } from "node:fs";
import { join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const genDir = join(root, "src", "gen");
const firstPartyRoot = join(genDir, "io", "altessa");

if (!existsSync(firstPartyRoot)) {
  console.error(
    `gen-index: ${relative(root, firstPartyRoot)} not found — generated code missing?`,
  );
  process.exit(1);
}

function walk(dir) {
  const out = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(p));
    else if (entry.isFile() && entry.name.endsWith("_pb.ts")) out.push(p);
  }
  return out;
}

function aliasFor(relFromGen) {
  const segs = relFromGen.split("/");
  segs[segs.length - 1] = segs[segs.length - 1].replace(/_pb\.ts$/, "");
  const ns = segs.slice(2); // drop the constant "io/altessa" prefix
  if (ns.length >= 3 && ns[ns.length - 1] === ns[0]) ns.pop();
  return ns.join("_");
}

const files = walk(firstPartyRoot)
  .map((p) => relative(genDir, p).split(sep).join("/"))
  .sort();

const lines = files.map((rel) => {
  const alias = aliasFor(rel);
  const spec = "./gen/" + rel.replace(/\.ts$/, ".js");
  return `export * as ${alias} from "${spec}";`;
});

const header = `// AUTOGENERATED by scripts/gen-index.mjs — DO NOT EDIT.
// Re-exports of the generated proto modules, one namespace per proto file.
// Regenerated on every build (npm \`prebuild\`) so this barrel always matches
// the generated tree under src/gen. Consumers can also import directly from
// the subpaths exposed in package.json, e.g.:
//
//   import { ServiceInfoService } from "@altessa-s/proto-gen-typescript/io/altessa/serviceinfo/v1/serviceinfo_service_pb.js";
`;

writeFileSync(join(root, "src", "index.ts"), header + "\n" + lines.join("\n") + "\n");
process.stdout.write(`gen-index: wrote src/index.ts (${lines.length} modules)\n`);
