// AUTOGENERATED by scripts/gen-index.mjs — DO NOT EDIT.
// Re-exports of the generated proto modules, one namespace per proto file.
// Regenerated on every build (npm `prebuild`) so this barrel always matches
// the generated tree under src/gen. Consumers can also import directly from
// the subpaths exposed in package.json, e.g.:
//
//   import { ServiceInfoService } from "@altessa-s/proto-gen-typescript/io/altessa/serviceinfo/v1/serviceinfo_service_pb.js";

export * as badrequest_v1 from "./gen/io/altessa/badrequest/v1/badrequest_pb.js";
export * as serviceinfo_v1 from "./gen/io/altessa/serviceinfo/v1/serviceinfo_pb.js";
export * as serviceinfo_v1_serviceinfo_service from "./gen/io/altessa/serviceinfo/v1/serviceinfo_service_pb.js";
export * as type_v1_contact from "./gen/io/altessa/type/v1/contact_pb.js";
export * as type_v1_date_period from "./gen/io/altessa/type/v1/date_period_pb.js";
export * as type_v1_document_ref from "./gen/io/altessa/type/v1/document_ref_pb.js";
export * as type_v1_file_ref from "./gen/io/altessa/type/v1/file_ref_pb.js";
export * as type_v1_gender from "./gen/io/altessa/type/v1/gender_pb.js";
export * as type_v1_label from "./gen/io/altessa/type/v1/label_pb.js";
export * as type_v1_location_privacy from "./gen/io/altessa/type/v1/location_privacy_pb.js";
export * as type_v1_money_range from "./gen/io/altessa/type/v1/money_range_pb.js";
export * as type_v1_organization_type from "./gen/io/altessa/type/v1/organization_type_pb.js";
